app:
  cbr-base-api: http://www.cbr.ru/
  cache-ttl: 1h

spring:
  application:
    name: currency-api

resilience4j:
  circuitbreaker:
    instances:
      cbr-client:
        sliding-window-type: count_based
        register-health-indicator: true
        sliding-window-size: 3
        record-exceptions:
          - java.lang.Exception
server:
  port: 8070
