app:
  api-version: v1.4
  kudago-api-base-url: https://kudago.com/public-api/${app.api-version}
  currency-api-base-url: http://localhost:8070
  pool-size: 5
  update-delay: 1h
  enable-update: true

custom-aspect:
  rate-limiter-config:
    enable: true
    acquire-timeout: 5s
    permits: 10

spring:
  application:
    name: kudago-api

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml
#  level:
#    root: debug
#    org:
#      springframework:
#        web: trace
#      apache: trace
#debug: true
