name: KudagoApi build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/kudago-api.yml
      - kudago-api/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      packages: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew kudago-api:build jacocoTestReport

      - name: docker build image
        run: docker image build -f kudago-api.Dockerfile -t ghcr.io/nevinture/kudago-api:latest .

      - name: publish image
        run: |
          docker login --username nevinture --password ${{ secrets.GHCR_TOKEN }} ghcr.io
          docker push ghcr.io/nevinture/kudago-api:latest

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        if: ( github.event_name != 'workflow_dispatch' )
        with:
          paths: ${{ github.workspace }}/kudago-api/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 30
          min-coverage-changed-files: 30
          title: Code Coverage
          update-comment: true

  checkstyle:
    name: checkstyle
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - run: |
          chmod +x gradlew
          ./gradlew CheckstyleMain